In [1]:
from utilities import LRfactors
from vanishing_odd import vanishingEvenGrass, vanishingOddGrass, extOddGrass, is_Lefschetz_excep, is_Lefschetz_basis, Lefschetz_indep
from complex import truncated_complex, complex_summand, complex, complex_entry, staircase
import numpy as np
import pprint as pp

In [2]:
k = 3
n = 5

exceptional = list(range(1,2*n+2-k))
ortho = list(range(0,2*n+2-k))

In [3]:
except_bundles=[]
for i in range(0,n+1):
    for j in range(i,n+1 - i):
        test = np.array([i,0,-j])
        if is_Lefschetz_excep(test,k,n):
            except_bundles.append(test)
            except_bundles.append(-test[::-1])
pp.pprint(except_bundles)

[array([0, 0, 0]),
 array([0, 0, 0]),
 array([ 0,  0, -1]),
 array([1, 0, 0]),
 array([ 0,  0, -2]),
 array([2, 0, 0]),
 array([ 0,  0, -3]),
 array([3, 0, 0]),
 array([ 0,  0, -4]),
 array([4, 0, 0]),
 array([ 0,  0, -5]),
 array([5, 0, 0]),
 array([ 1,  0, -1]),
 array([ 1,  0, -1]),
 array([ 1,  0, -2]),
 array([ 2,  0, -1]),
 array([ 1,  0, -3]),
 array([ 3,  0, -1]),
 array([ 1,  0, -4]),
 array([ 4,  0, -1]),
 array([ 2,  0, -2]),
 array([ 2,  0, -2])]


In [4]:
B1 = [[0,0,-3],[0,0,-2],[0,0,-1],[0,0,0],
   [1,0,-2],[1,0,-1],[1,0,0],
   [2,0,-2],[2,0,-1],[2,0,0],
   [3,0,-1],[3,0,0]] 

B2 = [[0,0,-2],[0,0,-1],[0,0,0],
   [1,0,-2],[1,0,-1],[1,0,0],
   [2,0,-2],[2,0,-1],[2,0,0],
   [3,0,-1],[3,0,0],[4,0,0]]

B = B1 + [[4,0,0]]

In [5]:
Lefschetz_indep([4,0,0], [0,0,-3], k, n)

[1, 2, 3, 4, 5, 6, 7, 8]

In [8]:
print(f"B1 is a Lefschetz basis? {is_Lefschetz_basis(B1,k,n)} \nB2 is a Lefschetz basis? {is_Lefschetz_basis(B2,k,n)} \nB is a Lefschetz basis? {is_Lefschetz_basis(B,k,n)}")

Problem with [4, 0, 0] [0, 0, -3]
B1 is a Lefschetz basis? True 
 B2 is a Lefschetz basis? True, B is a Lefschetz basis? False


In [7]:
split.left.display()

NameError: name 'split' is not defined

In [ ]:
new =split.right.tensor(split.right)
new.display()

 +  1 * U^(2, 0, 0)  +  1 * U^(1, 1, 0) [18]  
 +  22 * U^(1, 0, 0) [17]  
 +  121 * U^(0, 0, 0) [16]  


In [ ]:
s.shift(2)
s.display()


 +  1 * U^[1, 0, 0] [11]  
 +  11 * U^[0, 0, 0] [10]  
 +  330 * U^[-1, -1, -1] [9]  
 +  462 * U^[-1, -1, -2] [8]  
 +  462 * U^[-1, -1, -3] [7]  
 +  330 * U^[-1, -1, -4] [6]  
 +  165 * U^[-1, -1, -5] [5]  
 +  55 * U^[-1, -1, -6] [4]  
 +  11 * U^[-1, -1, -7] [3]  
 +  1 * U^[-1, -1, -8] [2]  


In [ ]:
prod = summer.tensor(second)
t = summer.tensor(second)

NameError: name 'summer' is not defined

In [ ]:
check = complex_entry()
check.display()

In [ ]:
new = prod.sum(t)
t.display()
new.display()

 +  121 * U^(2, 0, 0)  +  121 * U^(1, 1, 0)  +  242 * U^(2, 0, 0)  +  242 * U^(1, 1, 0) 

In [ ]:
prod_fin = new.tensor(t)
prod_fin.display()

 +  29282 * U^(4, 0, 0)  +  58564 * U^(2, 2, 0)  +  87846 * U^(3, 1, 0)  +  87846 * U^(2, 1, 1) 

In [ ]:
LRfactors([0,-1,-1], [0,-1,-1], 3)

{(0, -2, -2): 1, (-1, -1, -2): 1}

In [ ]:
vanishingEvenGrass([0,0,0],3,5)

False

In [ ]:
val = vanishingOddGrass([0,0,-1],3,5)
print(val)

(True, {})
